-- Login is the read boundary; any signed-in user can use existing stage RPCs.
begin;
set local lock_timeout = '10s';
revoke all on public."spin_geography" from public, anon;
revoke all on public."spin_contract_generation_runs" from public, anon;
revoke all on public."spin_contract_opportunities" from public, anon;
revoke all on public."spin_procurement_sources" from public, anon;
revoke all on public."procurement_sources" from public, anon;
revoke all on public."procurement_versions" from public, anon;
revoke all on public."procurement_events" from public, anon;
revoke all on public."procurement_runs" from public, anon;
revoke all on public."procurement_intake_items" from public, anon;
revoke all on public."procurement_registrations" from public, anon;
revoke all on public."procurement_contacts" from public, anon;
revoke all on public."procurement_lead_links" from public, anon;
revoke all on public."procurement_search_requests" from public, anon;
revoke all on public."procurement_request_sources" from public, anon;
revoke all on public."procurement_request_leads" from public, anon;
revoke all on public."procurement_intake_leads" from public, anon;
revoke all on public."procurement_event_receipts" from public, anon;
revoke all on public."procurement_members" from public, anon;
revoke all on public."procurement_leads" from public, anon;
revoke all on public."procurement_lead_notes" from public, anon;
revoke all on public."procurement_lead_note_edits" from public, anon;
revoke all on public."procurement_lead_stage_changes" from public, anon;
revoke all on public."procurement_geographies" from public, anon;
revoke all on public."procurement_place_counties" from public, anon;
revoke all on public."procurement_request_targets" from public, anon;
revoke all on public."procurement_source_capabilities" from public, anon;
revoke all on public."procurement_coverage_tasks" from public, anon;
revoke all on public."procurement_jobs" from public, anon;
revoke all on public."procurement_action_requests" from public, anon;
drop policy if exists "staff_read" on public."procurement_lead_links";
drop policy if exists "staff_read" on public."procurement_geographies";
drop policy if exists "lead_status_changes_read" on public."procurement_lead_stage_changes";
drop policy if exists "staff_read" on public."procurement_request_leads";
drop policy if exists "staff_read" on public."procurement_intake_items";
drop policy if exists "procurement_versions_read" on public."procurement_versions";
drop policy if exists "staff_read" on public."procurement_versions";
drop policy if exists "staff_read" on public."procurement_source_capabilities";
drop policy if exists "staff_read" on public."procurement_request_sources";
drop policy if exists "procurement_registrations_read" on public."procurement_registrations";
drop policy if exists "spin_contract_opportunities_read" on public."spin_contract_opportunities";
drop policy if exists "spin_contract_generation_runs_read" on public."spin_contract_generation_runs";
drop policy if exists "staff_read" on public."procurement_coverage_tasks";
drop policy if exists "spin_procurement_sources_read" on public."spin_procurement_sources";
drop policy if exists "staff_read" on public."procurement_place_counties";
drop policy if exists "staff_read" on public."procurement_intake_leads";
drop policy if exists "procurement_leads_read" on public."procurement_leads";
drop policy if exists "staff_read" on public."procurement_leads";
drop policy if exists "staff_read" on public."procurement_search_requests";
drop policy if exists "lead_notes_read" on public."procurement_lead_notes";
drop policy if exists "procurement_sources_read" on public."procurement_sources";
drop policy if exists "staff_read" on public."procurement_sources";
drop policy if exists "lead_note_edits_read" on public."procurement_lead_note_edits";
drop policy if exists "staff_read" on public."procurement_request_targets";
drop policy if exists "procurement_events_read" on public."procurement_events";
drop policy if exists "staff_read" on public."procurement_events";
drop policy if exists "procurement_runs_read" on public."procurement_runs";
drop policy if exists "procurement_contacts_read" on public."procurement_contacts";
drop policy if exists "staff_read" on public."procurement_contacts";
alter table public."spin_geography" enable row level security;
grant select on public."spin_geography" to authenticated;
drop policy if exists authenticated_read on public."spin_geography";
create policy authenticated_read on public."spin_geography" for select to authenticated using ((select auth.uid()) is not null);
alter table public."spin_contract_generation_runs" enable row level security;
grant select on public."spin_contract_generation_runs" to authenticated;
drop policy if exists authenticated_read on public."spin_contract_generation_runs";
create policy authenticated_read on public."spin_contract_generation_runs" for select to authenticated using ((select auth.uid()) is not null);
alter table public."spin_contract_opportunities" enable row level security;
grant select on public."spin_contract_opportunities" to authenticated;
drop policy if exists authenticated_read on public."spin_contract_opportunities";
create policy authenticated_read on public."spin_contract_opportunities" for select to authenticated using ((select auth.uid()) is not null);
alter table public."spin_procurement_sources" enable row level security;
grant select on public."spin_procurement_sources" to authenticated;
drop policy if exists authenticated_read on public."spin_procurement_sources";
create policy authenticated_read on public."spin_procurement_sources" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_sources" enable row level security;
grant select on public."procurement_sources" to authenticated;
drop policy if exists authenticated_read on public."procurement_sources";
create policy authenticated_read on public."procurement_sources" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_versions" enable row level security;
grant select on public."procurement_versions" to authenticated;
drop policy if exists authenticated_read on public."procurement_versions";
create policy authenticated_read on public."procurement_versions" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_events" enable row level security;
grant select on public."procurement_events" to authenticated;
drop policy if exists authenticated_read on public."procurement_events";
create policy authenticated_read on public."procurement_events" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_intake_items" enable row level security;
grant select on public."procurement_intake_items" to authenticated;
drop policy if exists authenticated_read on public."procurement_intake_items";
create policy authenticated_read on public."procurement_intake_items" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_contacts" enable row level security;
grant select on public."procurement_contacts" to authenticated;
drop policy if exists authenticated_read on public."procurement_contacts";
create policy authenticated_read on public."procurement_contacts" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_lead_links" enable row level security;
grant select on public."procurement_lead_links" to authenticated;
drop policy if exists authenticated_read on public."procurement_lead_links";
create policy authenticated_read on public."procurement_lead_links" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_search_requests" enable row level security;
grant select on public."procurement_search_requests" to authenticated;
drop policy if exists authenticated_read on public."procurement_search_requests";
create policy authenticated_read on public."procurement_search_requests" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_request_sources" enable row level security;
grant select on public."procurement_request_sources" to authenticated;
drop policy if exists authenticated_read on public."procurement_request_sources";
create policy authenticated_read on public."procurement_request_sources" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_request_leads" enable row level security;
grant select on public."procurement_request_leads" to authenticated;
drop policy if exists authenticated_read on public."procurement_request_leads";
create policy authenticated_read on public."procurement_request_leads" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_intake_leads" enable row level security;
grant select on public."procurement_intake_leads" to authenticated;
drop policy if exists authenticated_read on public."procurement_intake_leads";
create policy authenticated_read on public."procurement_intake_leads" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_leads" enable row level security;
grant select on public."procurement_leads" to authenticated;
drop policy if exists authenticated_read on public."procurement_leads";
create policy authenticated_read on public."procurement_leads" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_lead_notes" enable row level security;
grant select on public."procurement_lead_notes" to authenticated;
drop policy if exists authenticated_read on public."procurement_lead_notes";
create policy authenticated_read on public."procurement_lead_notes" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_lead_note_edits" enable row level security;
grant select on public."procurement_lead_note_edits" to authenticated;
drop policy if exists authenticated_read on public."procurement_lead_note_edits";
create policy authenticated_read on public."procurement_lead_note_edits" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_lead_stage_changes" enable row level security;
grant select on public."procurement_lead_stage_changes" to authenticated;
drop policy if exists authenticated_read on public."procurement_lead_stage_changes";
create policy authenticated_read on public."procurement_lead_stage_changes" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_geographies" enable row level security;
grant select on public."procurement_geographies" to authenticated;
drop policy if exists authenticated_read on public."procurement_geographies";
create policy authenticated_read on public."procurement_geographies" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_place_counties" enable row level security;
grant select on public."procurement_place_counties" to authenticated;
drop policy if exists authenticated_read on public."procurement_place_counties";
create policy authenticated_read on public."procurement_place_counties" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_request_targets" enable row level security;
grant select on public."procurement_request_targets" to authenticated;
drop policy if exists authenticated_read on public."procurement_request_targets";
create policy authenticated_read on public."procurement_request_targets" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_source_capabilities" enable row level security;
grant select on public."procurement_source_capabilities" to authenticated;
drop policy if exists authenticated_read on public."procurement_source_capabilities";
create policy authenticated_read on public."procurement_source_capabilities" for select to authenticated using ((select auth.uid()) is not null);
alter table public."procurement_coverage_tasks" enable row level security;
grant select on public."procurement_coverage_tasks" to authenticated;
drop policy if exists authenticated_read on public."procurement_coverage_tasks";
create policy authenticated_read on public."procurement_coverage_tasks" for select to authenticated using ((select auth.uid()) is not null);
revoke execute on function procurement_lead_changed() from public, anon;
revoke execute on function pending_procurement_events(text,integer) from public, anon;
revoke execute on function ingest_procurement_lead(uuid,text,jsonb,text,uuid,text,text,uuid) from public, anon;
revoke execute on function queue_recompete_reviews() from public, anon;
revoke execute on function edit_lead_note(uuid,text) from public, anon;
revoke execute on function update_procurement_lead_stage(uuid,text,text,text) from public, anon;
revoke execute on function bulk_update_procurement_lead_stage(uuid[],text,text,text) from public, anon;
revoke execute on function procurement_parse_date(text) from public, anon;
revoke execute on function procurement_parse_deadline(text) from public, anon;
revoke execute on function procurement_sync_lead_columns() from public, anon;
revoke execute on function create_lead_note(uuid,text) from public, anon;
revoke execute on function spin_touch_updated_at() from public, anon;
revoke execute on function validate_procurement_search_request() from public, anon;
revoke execute on function ingest_procurement_intake(uuid,text,jsonb,text) from public, anon;
revoke execute on function acknowledge_procurement_event(text,uuid) from public, anon;
notify pgrst, 'reload schema';
commit;
